package datasource;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;

// file must start with @@startuml <name>

public class PlantUMLWriter {

    private StringBuilder code;
    private Path outputPath;

    public PlantUMLWriter(StringBuilder incoming, Path path){
        this.code = incoming;
        this.outputPath = path;
        writeAndClose();
    }
    
    private void writeAndClose(){
        try (BufferedWriter buf = Files.newBufferedWriter(outputPath, StandardOpenOption.CREATE)){
            buf.write("@@startuml Autogenerated PlantUML\n\n");
            buf.write(code.toString());
            buf.close();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

}
